int64 seq
string UID

uint32 ram_use 
uint32 ram_max

uint32 swap_use #Swap memory used
uint32 swap_max #Maximum swap memory
uint32 swap_cache 

uint32 emc_usage

uint32 cpu_core0_usage
uint32 cpu_core0_freq
uint32 cpu_core1_usage
uint32 cpu_core1_freq
uint32 cpu_core2_usage
uint32 cpu_core2_freq
uint32 cpu_core3_usage
uint32 cpu_core3_freq
uint32 cpu_core4_usage
uint32 cpu_core4_freq
uint32 cpu_core5_usage
uint32 cpu_core5_freq
uint32 cpuTemp

uint32 gr3d_usage #GPU usage 
uint32 gr3d_freq #GPU Freqency
uint32 gpuTemp
