[About]
VERSION=2.0.20-beta

[Settings]

# HOSTS
ALG_HOST=alg
CCD_HOST=ccd
CV_HOST=cv
CVN_HOST=cvn
STREAMCV_HOST=streamcv
DB_HOST=db
GEO_HOST=geo
LSC_HOST=lsc
MAV_HOST=NET_IP
NGINX_HOST=NET_IP
ODM_HOST=odm
ROS_HOST=NET_IP
RTMP_HOST=rtmp
WEB_HOST=web
WS_HOST=ws
WSI_HOST=wsi
WSM_HOST=wsm
KC_HOST=kc
DRID_HOST=drid

# IP configuration
SUBNET=192.168.2.0/24
GATEWAY=192.168.2.1
DB_WHITELIST=192.168.2.0/24 192.168.3.0/24

# IP ADDRESS
ALG_IP=192.168.2.243
CCD_IP=192.168.2.244
CV_IP=192.168.2.245
CVN_IP=192.168.2.246
STREAMCV_IP=192.168.2.238
DB_IP=192.168.2.247
GEO_IP=192.168.2.248
LSC_IP=192.168.2.249
MAV_IP=NET_IP
NGINX_IP=NET_IP
ODM_IP=192.168.2.250
ROS_IP=NET_IP
RTMP_IP=192.168.2.251
WEB_IP=192.168.2.252
WS_IP=192.168.2.253
WSI_IP=192.168.2.254
WSM_IP=192.168.2.242
KC_IP=192.168.2.241
MEDIAMTX_IP=192.168.2.240
DRID_IP=192.168.2.239

# PORTS
ALG_API_PORT=8768
CV_API_PORT=8767
CVN_API_PORT=8760
STREAMCV_PORT=8000
DB_PORT=3306
# NOTE: GEO PORT Cant be Changed
GEO_PORT=8764
IUS_PORT=8001
LSC_API_PORT=8766
MAV_API_PORT=8769
NGINX_PORT=8888
ROS_API_PORT=8765
# NOTE: ODM PORT Cant be Changed
ODM_PORT=3000 
RTMP_PORT=1935
WEB_PORT=8000
# ASGI (daphne) port for django's websockets, e.g. /ws/chat/
WEB_WS_PORT=8002
WS_PORT=8772
WSI_PORT=8773
WSM_PORT=8774
KC_API_PORT=8763
KEYCLOAK_PORT=8083
# NOTE: MEDIAMTX PORT Cant be Changed
MEDIAMTX_PORT=8889
DRID_API_PORT=8759


#DJANGO
DB_ENGINE=django.contrib.gis.db.backends.mysql
ADMIN_USER=admin

# DATABASE
DB_DATABASE=aiders
DB_USER=aiders

# DATABASE CONNECTIONS
ALG_DB_CONNECTION_POOLS=2
CV_DB_CONNECTION_POOLS=2
CVN_DB_CONNECTION_POOLS=2
LSC_DB_CONNECTION_POOLS=2
MAV_DB_CONNECTION_POOLS=2
ROS_DB_CONNECTION_POOLS=4
KC_DB_CONNECTION_POOLS=2
DRID_DB_CONNECTION_POOLS=2

# Legacy LSC: Set to 1 to use the legacy live stream capture (LSC) method, otherwise set to 0 for the new WebRTC-based stream.
LEGACY_LSC=0 

#KAFKA
KAFKA_ACTIVE=0
KAFKA_LOCAL=1
KAFKA_LOCAL_IP=NET_IP
KAFKA_IP=apps.edutel.uniwa.gr
KAFKA_PORT=9092
KAFKA_TELEMETRY_TOPIC=UAV_Telemetry
KAFKA_PATH_PLANNING_OUTPUT_TOPIC = PathPlanning_Mission_Output
KAFKA_OBJECT_DETECTION_TOPIC=ObjectDetection
KAFKA_CRISIS_CLASSIFICATION_TOPIC=CrisisClassification

#KAFKA seperate groups
KAFKA_GROUP_ID=kios_group
KAFKA_TELEMETRY_GROUP_ID=uav_telemetry_kios_group
KAFKA_PATH_PLANNING_OUTPUT_GROUP_ID=pathplanning_output_kios_group
KAFKA_CRISIS_CLASSIFICATION_GROUP_ID=crisisclassification_kios_group
KAFKA_OBJECT_DETECTION_GROUP_ID=objectdetections_kios_group

# WEATHER FETCH
ENABLE_WEATHER_FETCH=1


# MTX AUTH - HARD-CODED IN MEDIAMTX YML
MTX_USER=aiders
MTX_PASS=abcd1234


# KEYCLOAK
[Keycloak]
KEYCLOAK_ACTIVE=1
KEYCLOAK_IP=NET_IP
KEYCLOAK_DB_VENDOR=postgres
KEYCLOAK_DB_ADDR=keycloak-db
KEYCLOAK_DB_DATABASE=keycloakdb
KEYCLOAK_DB_USER=keycloakdbusr
KEYCLOAK_ADMIN=keycloakadmin
KEYCLOAK_DJANGO_CLIENT_ID=aiders-web-client

