FROM python:3.9

# Install required dependencies
RUN apt-get update && apt-get install -y \
    netcat-traditional \
    libgl1-mesa-dri \
    libgl1 \
    libglu1-mesa && \
    rm -rf /var/lib/apt/lists/*

# Copy the python dependencies
COPY mav/requirements.txt /app/requirements.txt
# Install Python dependencies
RUN pip install -r /app/requirements.txt

# copy the entrypoint bash script
COPY mav/entrypoint.mav.sh .

# Copy the python application
COPY mav/app /app

# HealthCheck
HEALTHCHECK --interval=30s CMD curl --fail http://localhost:${MAV_API_PORT}/mav/healthCheck || exit 1

# run the entrypoint bash script
ENTRYPOINT ["/bin/bash", "./entrypoint.mav.sh"]