# Latitude (degrees). Positive is north of equator; negative is south.
float64 latitude
# Longitude (degrees). Positive is east of prime meridian, negative west.
float64 longitude
# Altitude (meters). Positive is above reference (e.g., sea level).
float64 altitude
# Ground speed (meters/second)
float64 speed
# Gimbal angle (degrees)
string gimbalAngle
# Stay time above the waypoint (milliseconds)
int16 stayTime
# Take picture at waypoint
bool photo
