# location
float64 latitude
float64 longitude
float64 altitude
float64 heading

# orientations
float64 orientation_x
float64 orientation_y
float64 orientation_z

# accelerometer
float64 accelerometer_x
float64 accelerometer_y
float64 accelerometer_z

# gyroscope
float64 gyroscope_x
float64 gyroscope_y
float64 gyroscope_z

# geomagnetic
float64 geomagnetic_x
float64 geomagnetic_y
float64 geomagnetic_z

# light
float64 light

# step numbers:
float64 step

# pressure
float64 pressure

# proximity
float64 proximity

float64 battery_percentage