set(_CATKIN_CURRENT_PACKAGE "kios")
set(kios_VERSION "0.0.0")
set(kios_MAINTAINER "the0s <theodosis8@hotmail.com>")
set(kios_PACKAGE_FORMAT "2")
set(kios_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "gps_common" "python-numpy" "message_generation")
set(kios_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(kios_BUILDTOOL_DEPENDS "catkin")
set(kios_BUILDTOOL_EXPORT_DEPENDS )
set(kios_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "gps_common" "python-numpy" "message_runtime")
set(kios_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "gps_common" "python-numpy" "message_runtime")
set(kios_TEST_DEPENDS )
set(kios_DOC_DEPENDS )
set(kios_URL_WEBSITE "")
set(kios_URL_BUGTRACKER "")
set(kios_URL_REPOSITORY "")
set(kios_DEPRECATED "")