# Use the official Golang image as the base image
FROM golang:1.20 AS builder

# Set the working directory inside the container
WORKDIR /application

# Copy the rest of the application source code into the container
COPY ws/app/ .

CMD ["tail", "-f", "/dev/null"]

