FROM python:3.9

# Install required dependencies
RUN apt-get update && apt-get install -y \ 
    netcat-traditional \
    libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*

# Copy the python dependencies
COPY lsc/requirements.txt /app/requirements.txt
# Install Python dependencies
RUN pip install -r /app/requirements.txt

# copy the entrypoint bash script
COPY lsc/entrypoint.lsc.sh .

# Copy the python application
COPY lsc/app /app

# Expose the port for the webserver
EXPOSE 8766

# run the entrypoint bash script
ENTRYPOINT ["/bin/bash", "./entrypoint.lsc.sh"]