droneNames = [
    "SIM_Alpha",
    "SIM_Bravo",
    "SIM_Charlie",
    "SIM_Delta",
    "SIM_Echo",
    "SIM_Foxtrot",
    "SIM_Golf",
    "SIM_Hotel",
    "SIM_India",
    "SIM_Juliet",
    "SIM_Kilo",
    "SIM_Lima",
    "SIM_Mike",
    "SIM_November",
    "SIM_Oscar",
    "SIM_Papa",
    "SIM_Quebec",
    "SIM_Romeo",
    "SIM_Sierra",
    "SIM_Tango",
    "SIM_Uniform",
    "SIM_Victor",
    "SIM_Whiskey",
    "SIM_Xray",
    "SIM_Yankee",
    "SIM_Zulu",
    "SIM_Admiral",
    "SIM_Bandit",
    "SIM_Captain",
    "SIM_Dagger",
    "SIM_Eagle",
    "SIM_Falcon",
    "SIM_Gunner",
    "SIM_Hawk",
    "SIM_Iceman",
    "SIM_Jester",
    "SIM_King",
    "SIM_Lancer",
    "SIM_Maverick",
    "SIM_Ninja",
    "SIM_Outlaw",
    "SIM_Phantom",
    "SIM_Raptor",
    "SIM_Saber",
    "SIM_Tiger",
    "SIM_Viper",
    "SIM_Warrior",
    "SIM_Xeno",
    "SIM_Yardbird",
    "SIM_Zephyr"
]


droneModels = [
    "DJI Phantom 4 Pro",
    "Parrot Bebop 2",
    "Yuneec Typhoon H Pro",
    "Autel Robotics Evo",
    "DJI Mavic Air 2",
    "Holy Stone HS720",
    "Ryze Tello",
    "Potensic D85",
    "DJI Inspire 2",
    "Hubsan Zino Pro",
    "Walkera Vitus 320",
    "Autel Robotics EVO II",
    "DJI Mini 2",
    "Xiaomi Fimi X8 SE",
    "DJI Mavic 2 Pro",
    "Holy Stone HS100",
    "Yuneec Mantis G",
    "Potensic T25",
    "Ryze Tello EDU",
    "DJI Phantom 3 Pro",
    "Parrot Anafi",
    "Yuneec Typhoon H Plus",
    "Autel Robotics X-Star Premium",
    "DJI Mavic Air",
    "Holy Stone HS110D",
    "Potensic D58",
    "DJI Inspire 1",
    "Hubsan H501S X4",
    "Autel Robotics EVO Lite",
    "DJI Phantom 4 Advanced",
    "Ryze Tello Iron Man",
    "Yuneec Mantis Q",
    "Potensic D88",
    "DJI Mavic Mini",
    "Holy Stone HS200",
    "DJI Spark",
    "Autel Robotics X-Star",
    "Parrot Disco",
    "Yuneec Typhoon H3",
    "Hubsan H501A X4",
    "DJI Phantom 3 Standard",
    "Potensic D80",
    "DJI Mavic Pro",
    "Holy Stone HS160 Shadow",
    "Ryze Tello Boost Combo",
    "Autel X-Star Premium 2",
    "Yuneec Typhoon Q500 4K",
    "DJI Inspire 2 Pro",
    "Hubsan Zino",
    "Parrot Mambo",
    "DJI Phantom 4",
    "Potensic D85 GPS",
    "DJI Mavic Air 2S",
    "Holy Stone HS700D",
    "Ryze Tello EDU Pads"
]


deviceNames = [
    "SIM_Adam",
    "SIM_Alice",
    "SIM_Benjamin",
    "SIM_Bob",
    "SIM_Catherine",
    "SIM_Charlie",
    "SIM_Daniel",
    "SIM_David",
    "SIM_Emily",
    "SIM_Eve",
    "SIM_Fiona",
    "SIM_Frank",
    "SIM_George",
    "SIM_Grace",
    "SIM_Hannah",
    "SIM_Henry",
    "SIM_Isaac",
    "SIM_Isabella",
    "SIM_Jack",
    "SIM_Jennifer",
    "SIM_Karen",
    "SIM_Kevin",
    "SIM_Liam",
    "SIM_Lily",
    "SIM_Matthew",
    "SIM_Mia",
    "SIM_Natalie",
    "SIM_Nathan",
    "SIM_Olivia",
    "SIM_Oscar",
    "SIM_Penelope",
    "SIM_Peter",
    "SIM_Quentin",
    "SIM_Quincy",
    "SIM_Rachel",
    "SIM_Rebecca",
    "SIM_Samuel",
    "SIM_Samantha",
    "SIM_Tara",
    "SIM_Thomas",
    "SIM_Uma",
    "SIM_Ursula",
    "SIM_Victor",
    "SIM_Vincent",
    "SIM_Wendy",
    "SIM_Willa",
    "SIM_Xavier",
    "SIM_Yara",
    "SIM_Zoe",
    "SIM_Zorro"
]

deviceModels = [
    "iPhone 12",
    "Samsung Galaxy S21",
    "Google Pixel 5",
    "OnePlus 9 Pro",
    "Xiaomi Mi 11",
    "Sony Xperia 1 III",
    "LG Velvet",
    "Motorola Moto G Power",
    "Nokia 8.3",
    "Huawei P40 Pro",
    "Oppo Find X3 Pro",
    "Vivo X60 Pro",
    "Realme 8 Pro",
    "Lenovo Legion Phone",
    "Asus ROG Phone 5",
    "BlackBerry Key2",
    "HTC U12+",
    "Sony Xperia 5 II",
    "LG Wing",
    "Motorola Razr 5G",
    "Xiaomi Redmi Note 10",
    "Samsung Galaxy A52",
    "Google Pixel 4a",
    "OnePlus 8T",
    "iPhone SE (2020)",
    "Samsung Galaxy Note20",
    "Sony Xperia 10 III",
    "Nokia 5.4",
    "Motorola Edge+",
    "Huawei Mate 40 Pro",
    "Oppo Reno5 Pro+",
    "Vivo V21 5G",
    "Realme GT",
    "Lenovo Moto Z2 Force",
    "Asus ZenFone 8",
    "BlackBerry Evolve",
    "HTC Desire 20+",
    "Sony Xperia 1 II",
    "LG V60 ThinQ",
    "Motorola Moto G Stylus",
    "Xiaomi Mi 10T Pro",
    "Samsung Galaxy A71",
    "Google Pixel 4a 5G",
    "OnePlus Nord",
    "iPhone 11",
    "Samsung Galaxy S20 FE",
    "Sony Xperia 5",
    "Nokia 7.2",
    "Motorola Moto G9 Plus",
    "Huawei P30 Pro",
    "Oppo Reno4 Pro",
    "Vivo X50 Pro+",
    "Realme X7 Pro",
    "Nokia 3310"
]


loraMasterNames = [
    "SIM_LORA_MASTER_1",
    "SIM_LORA_MASTER_2",
    "SIM_LORA_MASTER_3",
]

loraClientNames = [
    'SIM_LORA_001',
    'SIM_LORA_002',
    'SIM_LORA_003',
    'SIM_LORA_004',
    'SIM_LORA_005',
    'SIM_LORA_006',
    'SIM_LORA_007',
    'SIM_LORA_008',
    'SIM_LORA_009',
    'SIM_LORA_010',
    'SIM_LORA_011',
    'SIM_LORA_012',
    'SIM_LORA_013',
    'SIM_LORA_014',
    'SIM_LORA_015',
    'SIM_LORA_016',
    'SIM_LORA_017',
    'SIM_LORA_018',
    'SIM_LORA_019',
    'SIM_LORA_020',
    'SIM_LORA_021',
    'SIM_LORA_022',
    'SIM_LORA_023',
    'SIM_LORA_024',
    'SIM_LORA_025',
    'SIM_LORA_026',
    'SIM_LORA_027',
    'SIM_LORA_028',
    'SIM_LORA_029',
    'SIM_LORA_030',
    'SIM_LORA_031',
    'SIM_LORA_032',
    'SIM_LORA_033',
    'SIM_LORA_034',
    'SIM_LORA_035',
    'SIM_LORA_036',
    'SIM_LORA_037',
    'SIM_LORA_038',
    'SIM_LORA_039',
    'SIM_LORA_040',
    'SIM_LORA_041',
    'SIM_LORA_042',
    'SIM_LORA_043',
    'SIM_LORA_044',
    'SIM_LORA_045',
    'SIM_LORA_046',
    'SIM_LORA_047',
    'SIM_LORA_048',
    'SIM_LORA_049',
    'SIM_LORA_050',
    'SIM_LORA_051',
    'SIM_LORA_052',
    'SIM_LORA_053',
    'SIM_LORA_054',
    'SIM_LORA_055',
    'SIM_LORA_056',
    'SIM_LORA_057',
    'SIM_LORA_058',
    'SIM_LORA_059',
    'SIM_LORA_060',
    'SIM_LORA_061',
    'SIM_LORA_062',
    'SIM_LORA_063',
    'SIM_LORA_064',
    'SIM_LORA_065',
    'SIM_LORA_066',
    'SIM_LORA_067',
    'SIM_LORA_068',
    'SIM_LORA_069',
    'SIM_LORA_070',
    'SIM_LORA_071',
    'SIM_LORA_072',
    'SIM_LORA_073',
    'SIM_LORA_074',
    'SIM_LORA_075',
    'SIM_LORA_076',
    'SIM_LORA_077',
    'SIM_LORA_078',
    'SIM_LORA_079',
    'SIM_LORA_080',
    'SIM_LORA_081',
    'SIM_LORA_082',
    'SIM_LORA_083',
    'SIM_LORA_084',
    'SIM_LORA_085',
    'SIM_LORA_086',
    'SIM_LORA_087',
    'SIM_LORA_088',
    'SIM_LORA_089',
    'SIM_LORA_090',
    'SIM_LORA_091',
    'SIM_LORA_092',
    'SIM_LORA_093',
    'SIM_LORA_094',
    'SIM_LORA_095',
    'SIM_LORA_096',
    'SIM_LORA_097',
    'SIM_LORA_098',
    'SIM_LORA_099',
    'SIM_LORA_100'
]
