FROM ros:noetic

RUN apt-get update && apt-get install -y python3-pip && pip3 install --upgrade pip
RUN python3 -V && pip3 -V
ENV DEBIAN_FRONTEND=noninteractive 

# Copy the python dependencies
COPY ssm/requirements.txt /app/requirements.txt
# Install Python dependencies
RUN pip install -r /app/requirements.txt

RUN apt-get update && apt-get install openjdk-11-jdk -y && apt-get install nano -y
RUN apt-get update && apt-get install -y cargo && apt-get install graphviz -y
RUN pip3 install pgmpy thrift==0.11.0 && pip3 install --index-url https://support.bayesfusion.com/pysmile-B/ pysmile
RUN pip3 install maturin

RUN apt-get update && apt-get install curl -y && apt-get install -y lsb-release
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update && apt-get install ros-noetic-ros-base -y
SHELL ["/bin/bash", "-c"]
RUN source /opt/ros/noetic/setup.bash && apt install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential

RUN apt update && apt-get install -y \
    netcat

# Copy the python application
COPY ssm/app /app

# Copy Sinadra ros messages
COPY ssm/ros_msgs_sinadra /opt/ros_ws/src/ros_msgs/ros_msgs_sinadra

# # Build custom ROS messages
RUN source /opt/ros/noetic/setup.bash && \
    cd /opt/ros_ws/src/ros_msgs/ros_msgs_sinadra && \
    catkin_make

# copy the entrypoint bash script
COPY ssm/entrypoint.ssm.sh .

# run the entrypoint bash script
ENTRYPOINT ["/bin/bash", "./entrypoint.ssm.sh"]